import type { Verdict } from "./types";

export const GOOD_PHRASES = [
  "SO VAI.",
  "METE FICHA.",
  "HOJE TEM.",
  "PARTIU AREIA.",
  "VAI SEM MEDO.",
  "JOGUE O QUANTO QUISER.",
  "SE NAO FOR HOJE, VAI QUANDO?",
  "SEM DESCULPA HOJE.",
  "PASSA O PROTETOR E VAI.",
  "QUADRA SECA. BOLA NA MAO.",
  "DIA DE SAIR AREIA ATE DA ALMA.",
  "O CEU DEU O LEVANTAMENTO. E SO CORTAR.",
  "A PREVISAO MANDOU CHAMAR O QUARTO.",
  "HOJE O BLOQUEIO E SO NA REDE.",
  "O TEMPO TA PEDINDO VOLEI.",
] as const;

export const MAYBE_PHRASES = [
  "DA JOGO... MAS FICA ESPERTO.",
  "VAI, MAS LEVA UMA TROCA DE ROUPA.",
  "TALVEZ DE BOM. TALVEZ DE BANHO.",
  "SAO PEDRO TA NO AQUECIMENTO.",
  "DA PRA ARRISCAR.",
  "O CEU AINDA NAO DECIDIU.",
  "TEM VOLEI. PROVAVELMENTE.",
  "METE FICHA, MAS SEM GARANTIA.",
  "CHANCE DE BANHO GRATIS.",
  "A QUADRA TA EM OBSERVACAO.",
  "VAI, MAS NAO RECLAMA SE CHOVER.",
  "SE ABRIR, CORRE PRA AREIA.",
  "O TEMPO TA NO 20 A 20.",
  "LEVA A BOLA E O PLANO B.",
  "HOJE E VOLEI COM EMOCAO EXTRA.",
] as const;

export const BAD_PHRASES = [
  "HOJE TA OSSO.",
  "HOJE O ADVERSARIO E SAO PEDRO.",
  "LEVA UM GUARDA-CHUVA. E TALVEZ UM BARCO.",
  "A QUADRA ENTROU NO MODO AQUATICO.",
  "MELHOR DEIXAR A MANCHETE PRA AMANHA.",
  "HOJE E DIA DE ASSISTIR VOLEI.",
  "A VONTADE EXISTE. O CLIMA NAO COLABORA.",
  "SO SE FOR VOLEI SUBAQUATICO.",
  "A BOLA VAI MOLHAR ANTES DO PRIMEIRO SAQUE.",
  "O TEMPO PEDIU TEMPO.",
  "AREIA? HOJE TA MAIS PRA LAMA.",
  "SAO PEDRO FECHOU A QUADRA.",
  "MELHOR GUARDAR A BOLA.",
  "O UNICO BLOQUEIO HOJE E O DO CLIMA.",
  "DA PRA JOGAR. SE VOCE FOR ANFIBIO.",
] as const;

const PHRASES_BY_VERDICT: Record<Verdict, readonly string[]> = {
  GOOD: GOOD_PHRASES,
  MAYBE: MAYBE_PHRASES,
  BAD: BAD_PHRASES,
};

export function getRandomPhrase(verdict: Verdict, random = Math.random): string {
  const phrases = PHRASES_BY_VERDICT[verdict];
  return phrases[Math.floor(random() * phrases.length)] ?? phrases[0] ?? "";
}
